server:
  port: ${SERVER_PORT:8002}

kafka:
  topics:
    # Consumed Events for Customer Alerts
    return-initiated: ${KAFKA_TOPIC_RETURN_INITIATED:returns.order.initiated.v1}
    return-label-ready: ${KAFKA_TOPIC_RETURN_LABEL_READY:returns.label.ready.v1}
    refund-completed: ${KAFKA_TOPIC_REFUND_COMPLETED:returns.refund.completed.v1}

spring:
  application:
    name: notification-service

  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.returns.common.event"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    name: "logs/notification-service.log"

resilience4j:
  retry:
    instances:
      emailServiceRetry: # Referenced in Java via @Retry(name = "emailServiceRetry")
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.mail.MailException