server:
  port: ${SERVER_PORT:8002}

kafka:
  topics:
    return-label-ready: returns.label.ready.v1

spring:
  application:
    name: notification-service
  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.grangloria.*"
        spring.json.type.mapping: "com.grangloria.gateway.event.ReturnLabelReadyEvent:com.grangloria.notification.event.ReturnLabelReadyEvent"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    name: "logs/notification-service.log"

resilience4j:
  retry:
    instances:
      emailServiceRetry: # The custom name of this specific retry policy. You reference this identifier in Java code via retryRegistry.retry("emailServiceRetry") or @Retry(name = "emailServiceRetry")
        max-attempts: 3 # The total number of try attempts
        wait-duration: 500ms # The initial delay before triggering the first retry
        enable-exponential-backoff: true # Increases the delay duration progressively after each failed attempt instead of retrying at fixed intervals.
        exponential-backoff-multiplier: 2 # This is the factor by which the wait time scales.
        retry-exceptions: # This is the list of exceptions that will trigger a retry.
          - org.springframework.mail.MailException