server:
  port: ${SERVER_PORT:8002}

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group # Unique group ID for Fan-out!
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.grangloria.returns.*"
        spring.json.type.mapping: "com.grangloria.returns.domain.model.ReturnInitiatedEvent:com.grangloria.returns.event.ReturnInitiatedEvent"
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name} # This is automatically added by Spring Boot
  health:
    defaults:
      enabled: false
    kafka:
      enabled: false

logging:
  file:
    name: "logs/notification-service.log"