version: '3.8'

services:
  # =============== SQL SERVER ==============
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: returns-sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD:-Hayeja123!}
      - MSSQL_PID=Developer
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/1433'" ]
      interval: 5s
      timeout: 3s
      retries: 10

  # =============== SQL SERVER INITIALIZER ==============
  sql-server-init:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: returns-sql-server-init
    depends_on:
      sql-server:
        condition: service_healthy
    entrypoint:
      - /bin/bash
      - -c
      - |
        echo "SQL Server is online. Verifying catalog schemas..."
        /opt/mssql-tools18/bin/sqlcmd -S sql-server -U sa -P "Hayeja123!" -C -Q "IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'returns_db') CREATE DATABASE returns_db;"
        /opt/mssql-tools18/bin/sqlcmd -S sql-server -U sa -P "Hayeja123!" -C -Q "IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'inventory_db') CREATE DATABASE inventory_db;"
        echo "Databases returns_db and inventory_db verified/created successfully. Shutting down initializer daemon."

  # =============== ZOOKEEPER ==============
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: returns-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # =============== KAFKA ==============
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: returns-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # =============== MICROSERVICES STACK ==============

  returns-orchestrator:
    build:
      context: ./returns-orchestrator
      dockerfile: Dockerfile
    container_name: returns-orchestrator
    ports:
      - "8000:8000"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_R2DBC_URL=r2dbc:mssql://sql-server:1433/returns_db
      - SPRING_R2DBC_USERNAME=sa
      - SPRING_R2DBC_PASSWORD=${DB_PASSWORD:-Hayeja123!}
      - CARRIER_SERVICE_URL=http://carrier-service:8004
    volumes:
      - ./logs:/app/logs
    depends_on:
      sql-server-init:
        condition: service_completed_successfully
      kafka:
        condition: service_started

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    container_name: returns-inventory-service
    ports:
      - "8001:8001"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_R2DBC_URL=r2dbc:mssql://sql-server:1433/inventory_db
      - SPRING_R2DBC_USERNAME=sa
      - SPRING_R2DBC_PASSWORD=${DB_PASSWORD:-Hayeja123!}
    volumes:
      - ./logs:/app/logs
    depends_on:
      sql-server-init:
        condition: service_completed_successfully
      kafka:
        condition: service_started

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: returns-notification-service
    ports:
      - "8002:8002"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    volumes:
      - ./logs:/app/logs
    depends_on:
      - kafka

  # =============== CARRIER MOCK SERVICE ==============
  # This Microservice serves as a mock external api. This is used to mimic a call to an external
  carrier-service:
    build:
      context: ./carrier-service
      dockerfile: Dockerfile
    container_name: returns-carrier-service
    ports:
      - "8003:8003"
    volumes:
      - ./logs:/app/logs

  # =============== APACHE CASSANDRA ==============
  cassandra:
    image: cassandra:latest
    container_name: returns-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=returns-cassandra-cluster
      - CASSANDRA_DC=datacenter1
    volumes:
      - cassandra-data:/var/lib/cassandra

  # =============== APACHE SPARK ==============
  spark-master:
    image: apache/spark:3.5.5
    container_name: returns-spark-master
    hostname: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8085:8080"
      - "7077:7077"

  spark-worker:
    image: apache/spark:3.5.5
    container_name: returns-spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8086:8081"

  # ====== OBSERVABILITY STACK ======
  prometheus:
    image: prom/prometheus:latest
    container_name: returns-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - kafka

  grafana:
    image: grafana/grafana:latest
    container_name: returns-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.4
    container_name: returns-promtail
    volumes:
      - ./logs:/var/log/apps
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  mssql-data:
  cassandra-data: