rootProject.name = 'returns-system'

// These are the folders Gradle will look for
include 'returns-service'
include 'carrier-service'
include 'notification-service'
include 'inventory-service'
include 'carrier-gateway'
include 'mock-carrier-simulator'
include 'refund-service'
include 'common-events' // common kafka events