server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-boot-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: app-logs
          __path__: /var/log/apps/**/*.log # Tells Promtail to read all log files in this container folder
    pipeline_stages:
      - regex:
          source: filename
          expression: '.*/(?P<application>[^/]+)\.log' # Automatically extracts the app name from the file name!
      - labels:
          application: