server:
  port: ${SERVER_PORT:8005}

kafka:
  topics:
    # Consumed Events
    return-label-ready: ${KAFKA_TOPIC_RETURN_LABEL_READY:returns.label.ready.v1}
    # Produced Events
    package-received: ${KAFKA_TOPIC_PACKAGE_RECEIVED:returns.package.received.v1}

spring:
  application:
    name: mock-carrier-simulator

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: carrier-simulator-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: "com.returns.common.event.ReturnLabelReadyEvent"

logging:
  level:
    root: INFO
    com.returns.simulator: DEBUG
  file:
    name: "logs/mock-carrier-simulator.log"