server:
  port: ${SERVER_PORT:8003}
  error:
    include-message: ${SERVER_ERROR_INCLUDE_MESSAGE:always}
    include-binding-errors: ${SERVER_ERROR_INCLUDE_BINDING_ERRORS:always}

carrier:
  name: ${CARRIER_NAME:Grangloria Freight}

spring:
  application:
    name: carrier-service

  main:
    web-application-type: reactive

# Springdoc OpenAPI / Swagger UI Configuration
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#    enabled: ${SPRINGDOC_ENABLED:true}
#  swagger-ui:
#    path: /swagger-ui.html
#    operationsSorter: method
#    enabled: ${SWAGGER_UI_ENABLED:true}

# Actuator & Prometheus Metrics
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# Logging Levels (Streams to stdout for Docker & CloudWatch)
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.returns.carrier: ${LOGGING_LEVEL_CARRIER:DEBUG}