server:
  port: ${SERVER_PORT:8003}
  error:
    include-message: always
    include-binding-errors: always

carrier:
  name: ${CARRIER_NAME:Grangloria Freight}

spring:
  application:
    name: carrier-service

  main:
    web-application-type: reactive

# Springdoc OpenAPI / Swagger UI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Actuator & Prometheus Metrics
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# Logging Levels & File Output
logging:
  level:
    root: INFO
    com.returns.carrier: DEBUG
  file:
    name: "logs/carrier-service.log"