server:
  port: ${SERVER_PORT:8000}

kafka:
  topics:
    # Produced Events
    return-initiated: returns.order.initiated.v1
    return-inventory: returns.inventory.update.v1

    # Consumed Events
    return-completed: returns.order.completed.v1
    return-label-generated: returns.label.generated.v1
    return-label-ready: returns.label.ready.v1

spring:
  application:
    name: return-service

  r2dbc:
    url: "r2dbc:mssql://localhost:1433/returns_db?encrypt=true&trustServerCertificate=true"
    username: sa
    password: ${DB_PASSWORD:Hayeja123!}
    pool:
      initial-size: 5
      max-size: 20

  sql:
    init:
      mode: never # Set to 'never' so schema.sql isn't re-run against existing tables on startup

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: return-service-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "com.grangloria.gateway.event.ReturnLabelReadyEvent:com.grangloria.returns.event.ReturnLabelReadyEvent,com.grangloria.carrier.event.ReturnLabelReadyEvent:com.grangloria.returns.event.ReturnLabelReadyEvent"

logging:
  level:
    root: INFO
    org.springframework.data.r2dbc: DEBUG
    com.grangloria.returns: DEBUG
    org.springframework.r2dbc.core.R2dbcEntityTemplate: DEBUG
    io.r2dbc.mssql: DEBUG
  file:
    name: "logs/return-service.log"

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    defaults:
      enabled: false
    kafka:
      enabled: false